class Language {
  static String skip = "Skip";
  static String getStarted = "Get Started";
  static String emailAddress = "Email Address";
  static String password = "Password";
  static String rememberMe = "Remember Me";
  static String forgotPassword = "Forgot Password";
  static String changePassword = "Change Password";
  static String signIn = "Sign In";
  static String login = "Login";
  static String logout = "Logout";
  static String haveNotAcct = "Don't have an account";
  static String signInToYourAct = "Sign in to your Account";
  static String addBalance = "Add Balance";
  static String freelancer = "Freelancer";
  static String deliveryDate = "Delivery Date:";
  static String dashboard = "Dashboard";
  static String postAJob = "Post a Job";
  static String myJob = "My Job";
  static String appliedList = "Applied List";
  static String myOrder = "My Orders";
  static String refund = "Refund";
  static String liveChat = "Live Chat";
  static String walletTransList = "Wallet Transaction List";
  static String wishlist = "Wishlist";
  static String privacyAndPolicy = "Privacy and Policy";
  static String termsAndCondition = "Terms and Condition";
  static String editProfile = "Edit Profile";
  static String accDelete = "Account Delete";
  static String viewDetails = "View Details";
  static String viewApplied = "View Applied";
  static String status = "Status:";
  static String featuredCategory = "Featured Category";
  static String ourServices = "Our Services";
  static String recentJob = "Recent Job";
  static String topSeller = "Top Sellers";
  static String serviceDetails = "Service Details";
  static String review = "Review";
  static String service = "Service";
  static String rate = "Rate";
  static String jobs = "Jobs";
  static String viewProfile = "View Profile";
  static String sendMessage = "Send Message";
  static String orderNow = "Order Now";
  static String applyNow = "Apply Now";
  static String jobDetails = "Job Details";
  static String jobDescription = "Job Description";
  static String memberSince = "Member Since";
  static String totalOrder = "Total Order";
  static String totalJob = "Total Job";
  static String sellerDetails = "Seller Details";
  static String location = "Location";
  static String gender = "Gender";
  static String language = "Language";
  static String skill = "Skill";
  static String aboutDescription = "About Description";
  static String education = "Education";
  static String createService = "Create Service";
  static String manageService = "Manage Service";
  static String jobApplication = "Job Application";
  static String myWithdraw = "My Withdraw";
  static String home = "Home";
  static String inbox = "Inbox";
  static String order = "Order";
  static String more = "More";
  static String resendCode = "Resend Code";
}

// 'Skip' => 'Skip',
// 'Get Started' => 'Get Started',
// 'Email Address' => 'Email Address',
// 'Password' => 'Password',
// 'Remember Me' => 'Remember Me',
// 'Forgot Password' => 'Forgot Password',
// 'Change Password' => 'Change Password',
// 'Sign In' => 'Sign In',
// 'Login' => 'Login',
// 'Logout' => 'Logout',
// 'Dont have an account?' => 'Dont have an account?',
// 'Sign in to your Account' => 'Sign in to your Account',
// 'Add Balance' => 'Add Balance',
// 'Freelancer' => 'Freelancer',
// 'Delivery Date' => 'Delivery Date',
// 'Dashboard' => 'Dashboard',
// 'Post a Job' => 'Post a Job',
// 'My Job' => 'My Job',
// 'Applied List' => 'Applied List',
// 'My Orders' => 'My Orders',
// 'Refund' => 'Refund',
// 'Live Chat' => 'Live Chat',
// 'Wallet Transaction List' => 'Wallet Transaction List',
// 'Wishlist' => 'Wishlist',
// 'Privacy and Policy' => 'Privacy and Policy',
// 'Terms and Condition' => 'Terms and Condition',
// 'Edit Profile' => 'Edit Profile',
// 'Account Delete' => 'Account Delete',
// 'View Details' => 'View Details',
// 'View Applied' => 'View Applied',
// 'Status' => 'Status',
// 'Featured Category' => 'Featured Category',
// 'Our Services' => 'Our Services',
// 'Recent Job' => 'Recent Job',
// 'Top Sellers' => 'Top Sellers',
// 'Service Details' => 'Service Details',
// 'Review' => 'Review',
// 'Service' => 'Service',
// 'Rate' => 'Rate',
// 'Jobs' => 'Jobs',
// 'View Profile' => 'View Profile',
// 'Send Message' => 'Send Message',
// 'Order Now' => 'Order Now',
// 'Apply Now' => 'Apply Now',
// 'Job Details' => 'Job Details',
// 'Job Description' => 'Job Description',
// 'Member Since' => 'Member Since',
// 'Total Order' => 'Total Order',
// 'Total Job' => 'Total Job',
// 'Seller Details' => 'Seller Details',
// 'Location' => 'Location',
// 'Gender' => 'Gender',
// 'Language' => 'Language',
// 'Skill' => 'Skill',
// 'About Description' => 'About Description',
// 'Education' => 'Education',
// 'Create Service' => 'Create Service',
// 'Manage Service' => 'Manage Service',
// 'Job Application' => 'Job Application',
// 'My Withdraw' => 'My Withdraw',
// 'Home' => 'Home',
// 'Inbox' => 'Inbox',
// 'Order' => 'Order',
// 'More' => 'More',
// 'Resend Code' => 'Resend Code',