name: work_zone
description: "A new Flutter project."

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  http: ^1.4.0
  file_picker: ^10.1.7
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  pinput: ^5.0.1
  expandable_page_view: ^1.0.17
  shared_preferences: ^2.5.3
  webview_flutter: ^4.11.0
  rename: ^3.1.0
  #quill_html_editor: ^2.2.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.4
  flutter_widget_from_html: ^0.16.0
  #  html_editor_enhanced: ^2.6.0
  page_transition: ^2.2.1
  flutter_timer_countdown: ^1.0.7
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  path: ^1.9.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
