// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFY72nVsVRHFh5P6Q400sMsXmTq0I7zk',
    appId: '1:426080082956:web:37b696f4a05e4b9dc02229',
    messagingSenderId: '426080082956',
    projectId: 'trustboy-app',
    authDomain: 'trustboy-app.firebaseapp.com',
    storageBucket: 'trustboy-app.firebasestorage.app',
    measurementId: 'G-26CPLYP0DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo2Aq0GwrgOg4zNrxoq1p8nQYEMi2FaAI',
    appId: '1:426080082956:android:d9029e8fffd83059c02229',
    messagingSenderId: '426080082956',
    projectId: 'trustboy-app',
    storageBucket: 'trustboy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhhVUUGEhtUwl3ZR5Ip579waRkaxEU0OI',
    appId: '1:426080082956:ios:d26c5e97ad68891dc02229',
    messagingSenderId: '426080082956',
    projectId: 'trustboy-app',
    storageBucket: 'trustboy-app.firebasestorage.app',
    iosBundleId: 'com.trustboy.app',
  );
}
